-- HiPER final admin email-notification support.
-- Safe/idempotent repair for the delivery log used by notify-admin-application.
BEGIN;

CREATE TABLE IF NOT EXISTS public.notification_delivery_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_table text NOT NULL,
  record_id uuid NOT NULL,
  recipient_count integer NOT NULL DEFAULT 0,
  status text NOT NULL,
  provider_message_id text,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Repair older/partial versions of this table without replacing existing data.
ALTER TABLE public.notification_delivery_log
  ADD COLUMN IF NOT EXISTS source_table text,
  ADD COLUMN IF NOT EXISTS record_id uuid,
  ADD COLUMN IF NOT EXISTS recipient_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status text,
  ADD COLUMN IF NOT EXISTS provider_message_id text,
  ADD COLUMN IF NOT EXISTS error_message text,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

UPDATE public.notification_delivery_log
SET recipient_count = 0
WHERE recipient_count IS NULL;

UPDATE public.notification_delivery_log
SET created_at = now()
WHERE created_at IS NULL;

ALTER TABLE public.notification_delivery_log
  DROP CONSTRAINT IF EXISTS notification_delivery_log_source_table_check;
ALTER TABLE public.notification_delivery_log
  ADD CONSTRAINT notification_delivery_log_source_table_check
  CHECK (source_table IN (
    'ikes_applications',
    'asset_applications',
    'kpk_applications',
    'room_bookings',
    'donations'
  ));

ALTER TABLE public.notification_delivery_log
  DROP CONSTRAINT IF EXISTS notification_delivery_log_status_check;
ALTER TABLE public.notification_delivery_log
  ADD CONSTRAINT notification_delivery_log_status_check
  CHECK (status IN ('sent', 'skipped', 'failed'));

ALTER TABLE public.notification_delivery_log
  DROP CONSTRAINT IF EXISTS notification_delivery_log_recipient_count_check;
ALTER TABLE public.notification_delivery_log
  ADD CONSTRAINT notification_delivery_log_recipient_count_check
  CHECK (recipient_count >= 0);

CREATE INDEX IF NOT EXISTS idx_notification_delivery_log_source_record
  ON public.notification_delivery_log (source_table, record_id, created_at DESC);

ALTER TABLE public.notification_delivery_log ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.notification_delivery_log TO authenticated;
GRANT ALL ON public.notification_delivery_log TO service_role;

DO $do$
BEGIN
  IF to_regclass('public.notification_delivery_log_id_seq') IS NOT NULL THEN
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE public.notification_delivery_log_id_seq TO service_role';
  END IF;
END
$do$;

DROP POLICY IF EXISTS "Admins read notification logs" ON public.notification_delivery_log;
CREATE POLICY "Admins read notification logs"
  ON public.notification_delivery_log
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

COMMIT;
